# On a new commit: push new docs to anchorage-docs.github.io

name: Deploy docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Deploy:

    runs-on: ubuntu-latest
    environment: mpl-plotter-docs

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install pdoc3
        run: pip3 install pdoc3
      - name: Generate docs
        run:  pdoc --html mpl_plotter --force --output-dir=docs
      - name: Push new docs to anchorage-docs.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs/mpl_plotter'
          destination-github-username: 'mpl-plotter-docs'
          destination-repository-name: 'mpl-plotter-docs.github.io'
          user-email: antonlopezr99@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
