# LaTeX PDF destination
pdf_dir: 'docs'

# HOSTING CONFIGURATION
# =====================
# The generated HTML documentation may be hosted in a branch of this
# repository, or in a branch of any other repository to which you
# have writing rights to. To select either:
#   1. Uncomment the option of choice and comment the other
#   2. Input your preferences
# By default documentation will be hosted in this repo's docs branch.

# Host documentation in branch
branch: 'docs'
# Host documentation in repo
# user-email:         '<user>@<email.com>'
# dest-branch:        '<destination branch name>'
# dest-gh-username:   '<destination GitHub username>'
# dest-gh-repository: '<destination GitHub repository>'
user-email:         'antonlopezr99@gmail.com'
dest-branch:        'main'
dest-gh-username:   'mpl-plotter-docs'
dest-gh-repository: 'mpl-plotter-docs.github.io'