name: HOST:REPO Documentation Workflow

on:                       # Run action when changes are pushed or pull requests are accepted
  push:
    branches-ignore: 
      - 'docs'            # All except docs branch
  pull_request:
    branches-ignore:
      - 'docs'            # All except docs branch
  release:
    types: [ published ]

jobs:
  
  web:

    runs-on: ubuntu-latest
    env:
      docsdirectory: docs

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r $docsdirectory/source/requirements.txt
    - name: Generate
      run:  |
        cd $docsdirectory
        make html
        echo ::set-output name=html::${{ github.event.repository.name }}/$docsdirectory/build/html
      id: generate
    - name: Push
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: ${{ steps.generate.outputs.html }}
        destination-github-username: 'mpl-plotter-docs'
        destination-repository-name: 'mpl-plotter-docs.github.io'
        user-email: antonlopezr99@gmail.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: main
