name: Build and publish documentaion

# Trigger on changes to main branch or manually
on:
  push:
    branches: [ master ]
    paths:
      - mpl_plotter/
      - docs/**/*.md
      - docs/summary.py
      - docs/.doxybook/config.json
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  build_docs:
    # Pull pre-built docker image containing all dependencies
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      # Magic rsync command to replace genereated files and folders in top level docs
      # but preserve anything user made in the top level
      - name: Build docs
        run: |
          cd build
          cmake --build . --target docs
          rsync -av --delete --exclude 'images' ./doxybook2/output/* ../docs/code-base
          cd ../docs
          python3 summary.py

      # Render inplace SVG from DRAWIO
      # DRAWIO does not work in a docker container
      # Implement when this is sorted out
      # - name: Drawio
      #   run: |
      #     wget -nv --show-progress --progress=bar:force:noscroll https://github.com/jgraph/drawio-desktop/releases/download/v${DRAWIO_VERSION}/drawio-amd64-${DRAWIO_VERSION}.deb
      #     draw.io -x -f svg docs/*
      #   env:
      #     DRAWIO_VERSION: 14.5.1

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.API_TOKEN_GITHUB }}
          external_repository: mpl-plotter-docs/mpl-plotter-docs.github.io
          publish_branch: main  # default: gh-pages
          publish_dir: .