name: HOST:BRANCH Documentation Workflow

on:                       # Run action when changes are pushed or pull requests are accepted
  push:
    branches-ignore: 
      - 'docs'            # All except docs branch
    paths-ignore:
      - '**/docs_push_repo.yml'
  pull_request:
    branches-ignore:
      - 'docs'            # All except docs branch
  release:
    types: [ published ]

jobs:

  web:
    runs-on: ubuntu-latest
    env:
      docsdirectory: docs

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # =============================================
    - name: Load configuration variables into env
      # run: cat ${{ config.yml }} >> $GITHUB_ENV
      shell: bash
      run: |
        ls
        echo "==========================="
        while read line; do
          echo $line
          if "${line:0:1}" != "#"
          then
            echo "CONTENT"
            echo "$line" >> $GITHUB_ENV
            echo "++++++++++++++++++++++++++"
          else
            echo "--------------------------"
          fi
        done < config.yml
    - name: Check preferred way to store docs
      run: |
        if [ -z ${branch+x} ]
          then echo "::set-output name=host::BRANCH"
          else echo "::set-output name=host::REPO"
        fi
      id: host
    - name: Report host
      run: |
        echo "==========================="
        echo "${{ steps.host.outputs.host }}"
        echo "==========================="
    # =============================================
    # - name: Set up Python 3.7
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.7
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    #     pip install -r $docsdirectory/source/requirements.txt
    # - name: Generate
    #   run:  |
    #     cd $docsdirectory
    #     make html
    # - name: Stow
    #   run: |
    #     cd ..
    #     mkdir docs
    #     mv -v ${{ github.event.repository.name }}/$docsdirectory/build/html/* docs
    # - name: Switch
    #   uses: actions/checkout@v3
    #   with:
    #     ref: docs
    # - name: Set
    #   run: |
    #     mkdir -p docs
    #     cd docs
    #     rm -rf *
    # - name: Ready
    #   run: |
    #     mv -v ../docs/* docs
    #     touch .nojekyll
    # - name: Push
    #   run: |
    #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #     git config --local user.name "github-actions[bot]"
    #     git add -A && git commit --allow-empty -m "Updated Documentation"
    #     git push -u origin docs
