name: Documentation Workflow

on:                       # Run action when changes are pushed or pull requests are accepted
  push:
    branches-ignore: 
      - 'docs'            # All except docs branch
  pull_request:
    branches-ignore:
      - 'docs'            # All except docs branch
  release:
    types: [ published ]

jobs:

  web:
    runs-on: ubuntu-latest
    env:
      docsdirectory: doctest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r $docsdirectory/source/requirements.txt
    - name: Generate
      run:  |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git switch --orphan aux
        git commit --allow-empty -m "Created auxiliary branch"
        git push
        git rev-parse --abbrev-ref HEAD
        git checkout master -- $docsdirectory
        git commit -m "Copied docs setup from master"
        git push
      # make html
    # ---------------------------------------------------------------------------
    # - name: Generate
    #   run:  |
    #     cd $docsdirectory  
    #     make html
    #     echo ::set-output name=source::$docsdirectory/source/html
    #   id: html
    # - name: Push
    #   run: |
    #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #     git config --local user.name "github-actions[bot]"
    #     git commit -m "Documentation Updated" -a || echo "No changes to commit"
    #     git push
    # - name: Publish
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     publish_dir: ${{ steps.html.outputs.source }}
    #     publish_branch: docs
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     allow_empty_commit: true
    #     commit_message: ${{ github.event.head_commit.message }}
    #-------------------------------------------------------------------------------------------
        # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # external_repository: username/external-repository
    # - name: Commit
    #   run: |
    #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #     git config --local user.name "github-actions[bot]"
    #     git checkout docs
    #     git checkout master -- $docsdirectory/build/html
      # git restore --source master $docsdirectory/build/html
      # git add 
      # git commit -m "Documentation Updated"
      # git push 

    # with:
      #   persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
      #   fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: refs/heads/docs
