name: Documentation Workflow

on:                       # Run action when changes are pushed or pull requests are accepted
  push:
    branches-ignore: 
      - 'docs'            # All except docs branch
  pull_request:
    branches-ignore:
      - 'docs'            # All except docs branch
  release:
    types: [ published ]

jobs:

  web:
    runs-on: ubuntu-latest
    env:
      docDir: doctest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r doctest/source/requirements.txt
    - name: Generate docs
      run:  |
        cd $docDir
        make html
    - name: Commit documentation
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git stash push -- $docDir/build/html/*
        git checkout docs
        git stash pop
        git commit -m "Documentation Updated" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: docs
